all:
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
    ansible_become: yes
    ansible_become_method: sudo
  children:
    vagrant_env:
      hosts:
        openbsd2.example.gs:
          user: user
          user_passwd: "{{ host_user_passwd }}"
          root_passwd: "{{ host_root_passwd }}"
          ssh_pub_key: "{{ lookup('file', '~/.ssh/openbsd2_root.pub') }}"
          ansible_become_pass: "{{ host_user_passwd }}"
          ansible_python_interpreter: /usr/local/bin/python3

