Vagrant.configure("2") do |config|
  config.vm.define "linux1" do |node4|
    node4.vm.box = "centos/7"
    #node4.vm.network "private_network", ip: "192.168.33.40"
    node4.vm.network "public_network", type: "dhcp"
    node4.vm.hostname = "linux1.example.gs"
    node4.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    node4.vm.provision "file", source: "id_rsa", destination: "/tmp/id_rsa"
    node4.vm.provision "file", source: "id_rsa.pub", destination: "/tmp/id_rsa.pub"
    node4.vm.provision "shell", inline: <<-SHELL
      mkdir /root/.ssh
      mv /tmp/id_rsa /root/.ssh/id_rsa
      mv /tmp/id_rsa.pub /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      cat /root/.ssh/id_rsa >> /root/.ssh/authorized_keys
      --echo "nameserver 192.168.33.10" > /etc/resolv.conf
    SHELL
  end
end
